#!/bin/bash
# FIXED VARS AND CONSTANT ..
TAB=$(echo -ne "\t")

# BASE (CUSTOM) VARIABLES - They may vary depending on system environment
SDK_HOME=/opt/Android/Sdk
LIBSTDC_PATH=/usr/lib/x86_64-linux-gnu/libstdc++.so.6

EMULATOR_PATH=$SDK_HOME/emulator/emulator
WRITABLE="-writable-system"

function is_number() {
	VARIABLE=$1
	if [ $VARIABLE -eq $VARIABLE 2> /dev/null ]; then
		# echo $VARIABLE is a number
		isnumber=YES
	else
		isnumber=NO
	fi
}


# LD_PRELOAD='/usr/lib/x86_64-linux-gnu/libstdc++.so.6' ~/Android/Sdk/tools/emulator -netdelay none -netspeed full -avd Nexus_5_API_21

AVD="$1"

if [ -z "$1" ]; then
	listavds=`$EMULATOR_PATH -list-avds`
	param=""
else
	is_number $AVD
	if [ $isnumber = SI ]; then
		listavds=`$EMULATOR_PATH -list-avds`
		param="number"
	else
		listavds=`$EMULATOR_PATH -list-avds | grep -i $AVD`
		param="alpha"
	fi
fi

# Assegna avds
n=0
for i in $listavds
do
	n=$((n+1))
	avds[$((n-1))]="$i"
done

if [ "$param" = "number" ]; then
	if [ $param -gt $n ]; then
		echo "indice superire al numero AVD presentei. Scegliere da lista completa"
		listavds=`$EMULATOR_PATH -list-avds`
	elif [ $param -gt 0 ]; then
		avd2run=${avds[$((param-1))]}
		echo $avd2run
		LD_PRELOAD=$LIBSTDC_PATH $EMULATOR_PATH -netdelay none -netspeed full $WRITABLE -avd $avd2run &
		exit 0
	fi

else
	if [ $n -eq 1 ]; then
		avd2run=${avds[0]}
		echo $avd2run
		LD_PRELOAD=$LIBSTDC_PATH $EMULATOR_PATH -netdelay none -netspeed full $WRITABLE -avd $avd2run &
		exit 0
	elif [ $n -eq 0 ]; then
		echo "non trovata nessuna AVD nel pattern indicato. Scegliere da lista completa"
		listavds=`$EMULATOR_PATH -list-avds`
	fi
fi


n=0
for i in $listavds
do
	n=$((n+1))
	echo "$n) $i"
	avds[$((n-1))]="$i"
done


# echo -ne "Quale? "
scelta=""
while [ "$scelta" = "" ]
do
	echo -ne "Scelta : (tra 1 e $n, 0=esci) " 
	read scelta
	is_number $scelta
	if [ $isnumber = NO ]; then
		echo "$scelta non e' un numero. Riprova"
		scelta=""
		continue
	else
		scelta=$((scelta+0))
		# echo "scelta = $scelta"
	fi
	if [ $scelta -lt 0 -o $scelta -gt $n ]; then
		echo "Scelta non valida. Tra 1 e $n"'!'" (o 0 per uscire)"
		scelta=""
	fi
done

if [ $scelta -eq 0 ]; then
	exit
fi
avd2run=${avds[scelta-1]}
echo $avd2run
LD_PRELOAD=$LIBSTDC_PATH $EMULATOR_PATH -netdelay none -netspeed full $WRITABLE -avd $avd2run &
exit 0

